<?php

/**
 * @file
 * Contains test_guadalupe.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function test_guadalupe_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test_guadalupe module.
    case 'help.page.test_guadalupe':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My test module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function test_guadalupe_theme() {
  return [
    'test_guadalupe' => [
      'render element' => 'children',
    ],
  ];
}
